#include "ast-node-type.h"

#define CASE(ITEM) case ITEM: return #ITEM;

const char *getAstNodeTypeString(enum AstNodeType item) {
	switch(item) {
		CASE(NT_ADD_EXPR)
		CASE(NT_SUB_EXPR)
		CASE(NT_MUL_EXPR)
		CASE(NT_DIV_EXPR)

		CASE(NT_CALL_EXPR)
		CASE(NT_INDEX_EXPR)
		CASE(NT_ASSIGN_EXPR)

		CASE(NT_EXPR_LIST)
		CASE(NT_INIT_VAR_LIST)
		CASE(NT_ARG_DEF_LIST)
		CASE(NT_ARR_SIZE_DEF_LIST)
		CASE(NT_SRC)

		CASE(NT_INIT_VAR_STMT)
		CASE(NT_IF_STMT)
		CASE(NT_IF_ELSE_STMT)
		CASE(NT_WHILE_STMT)
		CASE(NT_DO_WHILE_STMT)
		CASE(NT_BREAK_STMT)
		CASE(NT_STMT_BLOCK)
		CASE(NT_STMT_BLOCK_INNER)

		CASE(NT_FUNC_SIGNATURE)
		CASE(NT_FUNC)
		CASE(NT_TYPE_REF)
		CASE(NT_ARG_DEF)

		default: return "UNKNOWN_NODE_TYPE";
	}
}